import React from 'react'
import Treanding from '../Trending/Trending'

function Recommendation() {
    const treanding  = {"page":1,"results":
                                    [
                                      {"backdrop_path":"/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg","title":"Luca","genre_ids":[16,35,10751,14],"original_language":"en","original_title":"Luca","poster_path":"/jTswp6KyDYKtvC52GbHagrZbGvD.jpg","video":false,"vote_average":8.1,"overview":"Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.","id":508943,"vote_count":2695,"release_date":"2021-06-17","adult":false,"popularity":3692.521,"media_type":"movie"},
                                      {"adult":false,"backdrop_path":"/kDQdFs5XL6G8TuXvd0NnJfQ59GP.jpg","genre_ids":[878,12,9648,28,53,14,35],"id":641501,"original_language":"fr","original_title":"Comment je suis devenu super-héros","poster_path":"/d0wn9YtEnmbucx8ZUsT918ctoiK.jpg","video":false,"vote_average":6.3,"overview":"Paris 2020. While superheroes have assimilated into the Parisian society, they discover a new drug that gives themselves personal superpowers to mere mortals. Lieutenants Moreau and Schaltzmann are investigating the case with the support of two ex-superheroes, Monte Carlo and Callista. They'll do whatever it takes to dismantle the traffic. But Moreau's past resurfaces, and the investigation becomes more complicated.","release_date":"2020-11-19","vote_count":101,"title":"How I Became a Superhero","popularity":263.684,"media_type":"movie"},
                                      {"video":false,"vote_average":7.6,"overview":"Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.","release_date":"2021-05-19","vote_count":540,"adult":false,"backdrop_path":"/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg","title":"F9","genre_ids":[28,12,80,53],"id":385128,"original_language":"en","original_title":"F9","poster_path":"/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg","popularity":2426.473,"media_type":"movie"},
                                      {"adult":false,"backdrop_path":"/5C8bfwglg91uZhc2fbfpSjNGamV.jpg","genre_ids":[27,9648],"original_language":"en","original_title":"Fear Street: 1994","poster_path":"/9J9Wy39ZjrVmfk7yMkulpcI5sy0.jpg","vote_count":475,"video":false,"vote_average":6.8,"title":"Fear Street: 1994","overview":"In 1994, a group of teenagers discovers that the terrifying events which have haunted their town for generations ​are all connected — and that they may be the next targets.","release_date":"2021-06-28","id":591273,"popularity":1921.347,"media_type":"movie"},
                                      {"adult":false,"backdrop_path":"/qPu6o2jle7ydBXPf6sph9Z5jtSP.jpg","genre_ids":[35,18],"original_language":"fr","original_title":"Le guide de la famille parfaite","poster_path":"/cBhkSwZpb3QpUwFuFdWAXTqWAtS.jpg","vote_count":2,"video":false,"vote_average":7.5,"title":"The Guide to the Perfect Family","overview":"A mainstream comedy that raises the question and humorously exposes the difficulty and complexity of raising children in a society of ultra performance, nourished by parents who, wanting to give the best to their children, end up suffocating them.","release_date":"2021-07-14","id":633954,"popularity":34.115,"media_type":"movie"},
                                      {"adult":false,"backdrop_path":"/dkkDuToxTRMh5lmJXfULEOQK1ZM.jpg","genre_ids":[16,35,10751,878],"original_language":"en","original_title":"Space Jam: A New Legacy","poster_path":"/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg","id":379686,"video":false,"title":"Space Jam: A New Legacy","overview":"When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.","release_date":"2021-07-08","vote_count":9,"vote_average":7.6,"popularity":1050.268,"media_type":"movie"},
                                      {"release_date":"2021-07-23","adult":false,"backdrop_path":"/uMClfgmBx89A3Exd83bpyhQHGcL.jpg","genre_ids":[878,53],"vote_count":0,"id":791568,"original_title":"Settlers","poster_path":"/tBUYDwiJVDcnjPneOitVetJk2Rt.jpg","title":"Settlers","video":false,"vote_average":0.0,"original_language":"en","overview":"Remmy and her parents, refugees from Earth, have found peace on the Martian outskirts until strangers appear in the hills beyond their farm. Told as a triptych, the film follows Remmy as she struggles to survive in an uneasy landscape.","popularity":61.285,"media_type":"movie"}, 
                                      {"vote_average":7.1,"overview":"Ever since he was a kid, Tylor Tuskmon has dreamed of becoming a Scarer just like his idol James P. Sullivan, and now that dream is about to come true... or not. The day he arrives at Monsters Incorporated to begin his dream job as a Scarer, he learns that scaring is out and laughter is in! After being reassigned to the Monsters, Inc. Facilities Team, Tylor sets his sights on a new goal: figuring out how to be funny and becoming a Jokester.","id":90461,"original_name":"Monsters at Work","origin_country":["US"],"backdrop_path":"/2O3ZRECju00Jod6LrVB3uRgZMXK.jpg","genre_ids":[10751,35,16],"original_language":"en","vote_count":436,"poster_path":"/2gxgwhcuSmI5xtexb0t9zGj43FS.jpg","name":"Monsters at Work","first_air_date":"2021-07-07","popularity":1050.291,"media_type":"tv"}, 
                                      {"backdrop_path":"/uPHXbrh9jlq2XgfjjTFlkJfgtOQ.jpg","genre_ids":[16,18,10759,10765],"original_language":"en","original_name":"Resident Evil: Infinite Darkness","origin_country":["US"],"id":110642,"vote_average":8.1,"first_air_date":"2021-07-08","overview":"Years after the horrors of Raccoon City, Leon and Claire find themselves consumed by a dark conspiracy when a viral attack ravages the White House.","vote_count":213,"name":"Resident Evil: Infinite Darkness","poster_path":"/xCHJq63FrXCJAF7v69Obd24siDF.jpg","popularity":216.336,"media_type":"tv"}, 
                                      {"vote_average":7.0,"overview":"Millions in stolen cash. Missing luxury bourbon. Watch ordinary people almost get away with these extraordinary heists in this true crime series.","id":127643,"original_name":"Heist","origin_country":["US"],"backdrop_path":"/nSMbU5Vqxw2QGmq5o6voRN4zSzA.jpg","genre_ids":[99,80],"original_language":"en","vote_count":1,"poster_path":"/ttG7SIqtuYRLSHJWE27zdY71hJo.jpg","name":"Heist","first_air_date":"2021-07-14","popularity":30.205,"media_type":"tv"}, 
                                      {"backdrop_path":"/9yBVqNruk6Ykrwc32qrK2TIE5xw.jpg","title":"Mortal Kombat","genre_ids":[28,14,12],"original_language":"en","original_title":"Mortal Kombat","poster_path":"/nkayOAUBUu4mMvyNf9iHSUiPjF1.jpg","video":false,"vote_average":7.5,"overview":"Washed-up MMA fighter Cole Young, unaware of his heritage, and hunted by Emperor Shang Tsung's best warrior, Sub-Zero, seeks out and trains with Earth's greatest champions as he prepares to stand against the enemies of Outworld in a high stakes battle for the universe.","id":460465,"vote_count":3292,"release_date":"2021-04-07","adult":false,"popularity":1077.591,"media_type":"movie"}, 
                                      {"backdrop_path":"/70AV2Xx5FQYj20labp0EGdbjI6E.jpg","genre_ids":[80,28,53],"original_language":"en","original_title":"Wrath of Man","poster_path":"/M7SUK85sKjaStg4TKhlAVyGlz3.jpg","id":637649,"title":"Wrath of Man","vote_count":1332,"overview":"A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.","release_date":"2021-04-22","vote_average":7.8,"video":false,"adult":false,"popularity":1828.252,"media_type":"movie"},
                                      {"original_language":"en","poster_path":"/8kOWDBK6XlPUzckuHDo3wwVRFwt.jpg","first_air_date":"2013-12-02","vote_average":8.8,"overview":"Rick is a mentally-unbalanced but scientifically-gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.","id":60625,"vote_count":4833,"name":"Rick and Morty","original_name":"Rick and Morty","origin_country":["US"],"genre_ids":[16,35,10765,10759],"backdrop_path":"/A9sCKnxgTTapzu307ybdXCJQEqD.jpg","popularity":1202.434,"media_type":"tv"}
                                    ]
                }
    return (
        <>
            <Treanding data={{title : "Similer movies", movies_data: treanding.results}}/>  
        </>
    )
}

export default Recommendation
